---
title: "compara_temperatura_verano"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r pkg}
library("tidyverse")
library("here")
library("patchwork")
library("egg")
```

# Datos de la estacion 
 
```{r}
dftemp <- read_csv(here::here("data/raw/psn07_temp_air.csv")) %>% 
  mutate(date = as.Date(time, format = "%Y-%m-%d")) %>% 
  dplyr::select(-variable_id) %>% 
  mutate(variable = case_when(variable == "temp_air" ~ "TemperaturaAire_Estacion"))

temp_psn <- dftemp %>% 
  filter(lubridate::year(date) %in% c(2018:2019)) %>% 
  mutate(location = "ESTACION", 
         replica = "R1")

```


# Datos de sensores 
- remove sensores con status elevation = 0 
- filter cota 1750 
```{r read_data}
sensors <- read_csv(here::here("data/raw/sensors.csv")) %>% 
  filter(elevation == 1750)

s <- read_csv(here::here("data/raw/readings.csv")) %>% 
  filter(id_sensor %in% sensors$id_sensor) %>% 
  dplyr::filter(str_detect(tag, "Temperatura")) %>% 
  dplyr::select(id_sensor, dat, time_dat, tag, positionsensor, tvariable) %>% 
  inner_join(sensors) %>% 
  dplyr::select(-tvariable, -elevation, -c(stationid:geo)) %>% 
  rename(pos = positionsensor) %>% 
  mutate(date = as.Date(time_dat, format = "%Y-%m-%d")) 

# humedad <- d %>% 
#   dplyr::filter(str_detect(tag, "Humedad")) %>% 
#   dplyr::select(id_sensor, dat, time_dat, tag, positionsensor, tvariable) %>% 
#   inner_join(sensors) %>% 
#   dplyr::select(-tvariable, -elevation, -c(stationid:geo)) %>% 
#   rename(pos = positionsensor) %>% as.data.frame()

```


# ¿cual fue el día mas caluroso de 2018? 
```{r}
t <- temp_psn %>% group_by(date) %>%
  summarise(value = mean(value)) 

t %>% ggplot(aes(x=date, y = value)) + geom_line()

t %>% filter(lubridate::year(date) == 2018) %>% filter(value == min(value))

```


- Seleccionar datos de un día de verano 
```{r, fig.height=8, fig.width=5}
# 19 Julio 2018 e.g.
f <- "2018-07-19"

psn10 <- temp_psn %>% filter(date == f) 
s10 <- s %>% filter(date == f) %>% 
  dplyr::select(time = time_dat, value = dat, variable = tag, date, 
                location, replica)

s10_avg <- s10 %>% group_by(time, date, location, variable) %>% 
  summarise(value = mean(value))

df10 <- bind_rows(psn10, s10_avg)


# %>% 
#   mutate(temp = case_when(
#     variable == "TemperaturaAire_Estacion" ~ "t.airEst",
# variable == "TemperaturaAire45altura" ~ "t.air45",
# variable == "TemperaturaSueloSuperficieCubierto" ~ "t.soil_surf.cub",
# variable == "TemperaturaSueloSuperficieDespejado" ~ "t.soil_surf.nocub",
# variable == "TemperaturaSuelo30profundidad" ~ "t.soil_30"))

df10 %>% ggplot(aes(x=time, y = value, colour = location)) + 
  geom_point() + facet_wrap(~variable)



ta <- df10 %>% 
  filter(str_detect(variable, "TemperaturaAire")) 

pta <- ta %>% ggplot(aes(x=time, y = value, colour = location)) + 
  geom_point() + geom_line() + 
  theme_bw() + 
  ylab("Temperatura del aire") 

tso <- df10 %>% 
  filter(str_detect(variable, "TemperaturaSuelo")) %>% 
  mutate(variableF = case_when(
    variable == "TemperaturaSueloSuperficieCubierto" ~ "Cubierto",
    variable == "TemperaturaSueloSuperficieDespejado" ~ "Despejado",
    variable == "TemperaturaSuelo30profundidad" ~ "Profundo"))

ptso <- tso %>% ggplot(aes(x=time, y = value, colour = location)) + 
  geom_point() + geom_line() + 
  facet_wrap(~variableF, ncol=1, strip.position = "right") + 
  theme_bw() +
  ylab("Temperatura del suelo")

```

```{r}

df10NA <- df10 %>% 
  filter(variable == "TemperaturaSueloSuperficieCubierto") %>% 
  filter(location == "CLARO") 

dfno <- expand.grid(time = df10NA$time, 
                    variable = c("TemperaturaSueloSuperficieCubierto",
                                 "TemperaturaSueloSuperficieDespejado",
                                 "TemperaturaSuelo30profundidad")) %>% 
  mutate(location = "ESTACION", 
         value = NA, 
         date = as.Date(time, format = "%Y-%m-%d"),
         replica = NA)
         


v <- bind_rows(df10, dfno) %>% 
  mutate(variableF = case_when(
    variable == "TemperaturaSueloSuperficieCubierto" ~ "b) Bajo piedra / Hojarasca",
    variable == "TemperaturaSueloSuperficieDespejado" ~ "c) Suelo superficie",
    variable == "TemperaturaSuelo30profundidad" ~ "d) Suelo -30cm", 
    variable == "TemperaturaAire_Estacion" ~ "a) Aire 45 cm", 
    variable == "TemperaturaAire45altura" ~ "a) Aire 45 cm")) %>% 
  mutate(timeF = as.Date(time, format="%Y-%m-%d %H:%m:%s"))

colores <- c("CLARO" = "#CC7722", "ROBLEDAL" = "#0B6623", "ESTACION" = "black")

l <- expand.grid(time = as.POSIXct("2018-07-19 02:00:00", format="%Y-%m-%d %H:%M:%S"),
                 variableF = unique(v$variableF),
                 value = Inf, 
                 location = "ESTACION")


perfil_temp <- v %>% ggplot(aes(x=time, y = value, colour = location)) + 
  geom_point(size=1) + geom_line() + 
  facet_wrap(~variableF, ncol=1, 
             strip.position = "right", scales = "free_y") + 
  theme_bw() +
  ylab("Temperatura (ºC)") + xlab("") + 
  theme(legend.position = "bottom",
        legend.title = element_blank(), 
        panel.grid = element_blank(), 
        strip.background = element_blank(), 
        strip.text = element_blank()) + 
  scale_x_datetime(breaks = scales::date_breaks("2 hours"),
                   date_labels = "%H") + 
  scale_color_manual(values=colores, 
                     labels = c("ESTACION"="Estación Meteorológica",
                                "CLARO" = "Open",
                                "ROBLEDAL" = "Forest")) +
  geom_text(data = l, aes(x=time, y=value, label = variableF),
            vjust = 1.5, hjust = 0,
            fontface = "bold", 
            colour = "black")

perfil_temp
```

```{r}
ggsave(plot = perfil_temp,
       filename = here::here("figs/profile_temperatura.jpg"), 
       width = 9, units = "cm",
       device = "jpg",
       dpi=300)

ggsave(plot = perfil_temp,
       filename = here::here("figs/profile_temperatura.pdf"), 
       height = 7, width = 4)
```

 










